export const REALTIME = {
  PROTOCOL_VERSION: 1,

  CONNECTION_TIMEOUT_MS: 10_000,

  HEARTBEAT_INTERVAL_MS: 25_000,

  RECONNECT: {
    INITIAL_DELAY_MS: 500,
    MAX_DELAY_MS: 15_000,
    BACKOFF_MULTIPLIER: 1.8,
    JITTER_RATIO: 0.2,
    MAX_ATTEMPTS: Infinity
  },

  CURSOR: {
    UPDATE_INTERVAL_MS: 50
  },

  MESSAGE: {
    MAX_SIZE_BYTES: 256 * 1024
  }
} as const;