"use client";

import {
  FormEvent,
  useState
} from "react";

import {
  useRouter
} from "next/navigation";

import {
  InvitationBackground
} from "@/components/couple-space/invitation-background";

function extractInvitationToken(
  value: string
): string | null {
  const trimmed =
    value.trim();

  if (!trimmed) {
    return null;
  }

  /*
   * Allow the user to paste the complete
   * invitation URL.
   *
   * Example:
   * https://example.com/invite/abc123
   */
  if (
    trimmed.startsWith("http://") ||
    trimmed.startsWith("https://")
  ) {
    try {
      const url =
        new URL(trimmed);

      const parts =
        url.pathname
          .split("/")
          .filter(Boolean);

      const inviteIndex =
        parts.indexOf("invite");

      if (inviteIndex === -1) {
        return null;
      }

      const token =
        parts[inviteIndex + 1];

      if (!token) {
        return null;
      }

      return decodeURIComponent(
        token
      );
    } catch {
      return null;
    }
  }

  /*
   * Also allow the user to paste:
   *
   * /invite/abc123
   */
  if (
    trimmed.startsWith("/invite/")
  ) {
    const token =
      trimmed
        .slice("/invite/".length)
        .split("/")[0];

    return token
      ? decodeURIComponent(token)
      : null;
  }

  /*
   * Finally, allow a raw token.
   *
   * Invitation tokens generated by the
   * backend use base64url characters.
   */
  if (
    /^[A-Za-z0-9_-]+$/.test(
      trimmed
    )
  ) {
    return trimmed;
  }

  return null;
}

export default function InvitePage() {
  const router =
    useRouter();

  const [
    value,
    setValue
  ] = useState("");

  const [
    error,
    setError
  ] = useState<string | null>(
    null
  );

  function handleSubmit(
    event: FormEvent<HTMLFormElement>
  ) {
    event.preventDefault();

    setError(null);

    const token =
      extractInvitationToken(
        value
      );

    if (!token) {
      setError(
        "Please paste a valid Couple Space invitation link."
      );

      return;
    }

    router.push(
      `/invite/${encodeURIComponent(
        token
      )}`
    );
  }

  return (
    <main className="invitation-screen">
      <InvitationBackground />

      <section
        className="invitation-card"
        aria-labelledby="invite-title"
      >
        <div
          className="auth-mark"
          aria-hidden="true"
        >
          ♡
        </div>

        <p className="auth-eyebrow">
          Couple Space
        </p>

        <h1
          id="invite-title"
          className="auth-title"
        >
          You have an invitation
        </h1>

        <p className="auth-description">
          Paste the invitation your person
          sent you and we&apos;ll take you to
          their private space.
        </p>

        <form
          onSubmit={handleSubmit}
        >
          <div className="invitation-input-group">
            <label
              className="invitation-input-label"
              htmlFor="invitation-link"
            >
              Invitation link
            </label>

            <input
              id="invitation-link"
              className="invitation-input"
              type="text"
              inputMode="url"
              autoComplete="off"
              spellCheck={false}
              placeholder="Paste your invitation link"
              value={value}
              onChange={(event) => {
                setValue(
                  event.target.value
                );

                if (error) {
                  setError(null);
                }
              }}
              autoFocus
            />
          </div>

          {error && (
            <p
              className="invitation-error"
              role="alert"
            >
              {error}
            </p>
          )}

          <button
            type="submit"
            className="invitation-continue"
          >
            Continue
          </button>
        </form>

        <p className="invitation-helper">
          Your invitation is private and
          can only be used while it is valid.
        </p>

        <button
          type="button"
          className="invitation-back"
          onClick={() =>
            router.push("/space")
          }
        >
          ← Back
        </button>
      </section>
    </main>
  );
}